
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE persoane[
<!ELEMENT persoane (persoana)>
<!ELEMENT persoana (nume,prenume,varsta,adresa)>
<!ELEMENT adresa (strada,numar,localitate,judet,tara)>
<!ELEMENT nume (#PCDATA)>
<!ELEMENT prenume (#PCDATA)>
<!ELEMENT varsta (#PCDATA)>
<!ELEMENT strada (#PCDATA)>
<!ELEMENT numar (#PCDATA)>
<!ELEMENT localitate (#PCDATA)>
<!ELEMENT judet (#PCDATA)>
<!ELEMENT tara (#PCDATA)>


]>
<persoane>
    <persoana id="1">
        <nume>Popescu</nume>
        <prenume>Ion</prenume>
        <varsta>23</varsta>
        <adresa>
            <strada>bd. Chimiei</strada>
            <numar>2</numar>
            <localitate>Vaslui</localitate>
            <judet>Vaslui</judet>
            <tara>Romania</tara>
        </adresa>
    </persoana>
</persoane>
